### ISSUE TITLE
Reference size for player in Unity

### ISSUE THREAD

**Issue by SKY0S** [Nolenz/WurstMod#1]
Talked w/ Anton, the **minimum** size you should be testing w/ is 2.1 units tall and 1.2 units wide.

[https://cdn.discordapp.com/attachments/507728191948062730/723300821327937566/unknown.png](url)

Taller is fine, that should be the minimum. Figured it would be nice information to have, for those of us that do not have access to VR testing, nor willing candidates.

If you need to contact me personally, my discord is Skyos#1111, I use that as my main source of social media, given the reputation of normal social media.

**Comment by nrgill28** [comment]
Moved to the [Mapping guidelines](https://github.com/Nolenz/WurstMod/wiki/Mapping-guidelines) page on the wiki
