### ISSUE TITLE
GitHub Wiki for documentation?

### ISSUE THREAD

**Issue by nrgill28** [Nolenz/WurstMod#10]
For documentation about mapping, usage of components, etc. we could open the repo's Wiki tab.
I have a couple of notes about Unity terrain and the documentation for classes included in my pull request.

**Comment by Nolenz** [comment]
I have been dragging my feet on proper documentation. Wiki has been opened.

**Comment by nrgill28** [comment]
Looks like the wiki is in collaborators-only mode

**Comment by Nolenz** [comment]
Hah, forgot about that setting. Should be fixed now.
