### ISSUE TITLE
Question about occlusion culling

### ISSUE THREAD

**Issue by devyndamonster** [Nolenz/WurstMod#11]
Does baked occlusion culling get exported with a map? I've been noticing that areas where occlusion culling should be working don't seem to have the performance expected. 

In the picture below, the occlusion culling is visualized in unity. Yet, in game when the player is facing towards the center of the map, there is still more lag than if they were facing away from the center.

![culling](https://user-images.githubusercontent.com/6070388/89135096-f6740d00-d4f8-11ea-938b-e3b0b330e271.PNG)

**Comment by Nolenz** [comment]
I'm fairly certain they are exported properly, I remember when I first started generating them I noticed better performance in my testing. Could have been a placebo effect though. I will try to investigate this a bit more closely.

Realtime lights seem to cause horrible performance, though. Try testing without your lights?

**Comment by devyndamonster** [comment]
The lighting is baked, not realtime. I'm going to continue investigating. It could be that aggressive occlusion culling is actually hurting performance since occlusion itself has a cost.
