### ISSUE TITLE
Possible inclusions for custom gamemodes

### ISSUE THREAD

**Issue by nrgill28** [Nolenz/WurstMod#15]
So a handful of people are interested in making custom game modes for H3, and if they were to actually create them it would be great to have support for that. Instead of only being able to export 'generic' or 'TNH', we could include a game mode text box in the `TNH_Level` script (Which also needs a new name now 😛) to allow for any arbitrary game modes and make the export process more generic.

Ideally, map validation can then be handled by either WustMod (for Take and Hold and Sandbox maps), or by another library in the Unity plugins folder. I have more ideas for how map validation can be improved but that's better saved for another issue.

Along with this, I think it would be beneficial to create a better map selection menu to accommodate a larger number of maps and maybe include search / filters.

The changes to exporting and validation would probably not be compatible with existing maps so all this can be saved until the next major update.

**Comment by Nolenz** [comment]
I agree with everything here. I think it's about time to get a 1.4 update out with the random little features and fixes we've added and start working on a snazzier, better organized, breaking 2.0 branch. Sounds like we both have a basic idea of what needs to get done, so I'll hit you up with direct repo access. Throw anything that isn't a bugfix onto the 2.0 branch at this point, I'd say.

We'll have to sit down and talk about a few things (like what form should the map selector take) and it's been hard for me to find the time recently between work and other commitments, but we'll get things moving.

**Comment by Nolenz** [comment]
Nathan got this in a while back, cleaning up.
