### ISSUE TITLE
Suggestion: Easy testing

### ISSUE THREAD

**Issue by Frityet** [Nolenz/WurstMod#18]
I could possibly script this myself, but basically what it is is that it opens h3 and loads your level for quick testing

**Comment by nrgill28** [comment]
I like this idea, and think it would be a great addition to v2.
I'll add it to the roadmap and if you'd like to implement it, feel free to do so and make a PR! 👍🏻

**Comment by Nolenz** [comment]
Implemented in WurstMod 2
