### ISSUE TITLE
Revise documentation

### ISSUE THREAD

**Issue by Amukakuma** [Nolenz/WurstMod#2]
I have h3vr updated and I've installed the mod (at least I think I have, the instructions are a bit lacking in specificity) and it doesn't work at all. No change to the t&h menu at all. can you offer any help?

**Comment by devyndamonster** [comment]
I also had trouble getting it working, and then I realized I was using the wrong BepInEx zip.
Try downloading the x64 version if you aren't already

**Comment by Nolenz** [comment]
I've clarified the readme to specifically mention downloading the x64 release of BepInEx. I will leave this open for now because my documentation is pretty terrible and I should do something about that.

**Comment by Amukakuma** [comment]
> I've clarified the readme to specifically mention downloading the x64 release of BepInEx. I will leave this open for now because my documentation is pretty terrible and I should do something about that.

thank you for the clarification, cheers :D

**Comment by Amukakuma** [comment]
> I've clarified the readme to specifically mention downloading the x64 release of BepInEx. I will leave this open for now because my documentation is pretty terrible and I should do something about that.

ok, so I've installed the x64 BepInEx, and then Wurstmod, still nothing. I don't think I'm doing the installation right, but the instructions are kinda vague. Do I just open the zip and drop in the master in or do I also open the master and drop what's in there into H3VR? A video installation would be really, really helpful

**Comment by nrgill28** [comment]
I think we could move _most_ of the stuff in the readme to wiki pages, linking to it from the readme instead.

**Comment by nrgill28** [comment]
The readme has been updated, guides and documentation have been moved to the repo Wiki.
