### ISSUE TITLE
Pmat script not working

### ISSUE THREAD

**Issue by JoshMate** [Nolenz/WurstMod#20]
When Applying the PMat script to an environment layer mesh collider (Like in the example maps) and setting it to iron + metal wall etc... it no longer generates: Hit effects, decals or bullet penetration. I have tried both the new and old PMAT in 1.4 and different types of colliders on the mesh but none work. 

The mesh still collides with the player/bullet but there is none of the new hit effects.

Sosigs and The barriers still ahve these effects (Anton's stuff)

**Comment by nrgill28** [comment]
Fixed in Wurst Mod 2.
