### ISSUE TITLE
Sosig Spawners Issue

### ISSUE THREAD

**Issue by JoshMate** [Nolenz/WurstMod#26]
Hi Guys,

My Sosigs that are spawning from sosig spawners are spawning in de-activated (Stationary with no reaction to exterior stimuli).

It is a fresh install of everything, fresh project, nav mesh built and sandbox map.

Here is my config:
![image](https://user-images.githubusercontent.com/50293237/100380516-eb486e00-300e-11eb-9045-4f0c47e224f5.png)

**Comment by nrgill28** [comment]
This has been addressed in [WurstMod 2.0.1.0](https://github.com/Nolenz/WurstMod/releases/tag/v2.0.1.0), thank you for the report!
