### ISSUE TITLE
Improve ResourceDef file generation

### ISSUE THREAD

**Issue by adolfobisi** [Nolenz/WurstMod#27]
Is there any method to make grababble objects? I see the "FVR Hand Grab Point" but that is probably used for ladders, or am I missing something there? Also, I dont quite understand how can i configure the "pointablebutton" to run other scripts. Thanks a lot for your work here!

**Comment by nrgill28** [comment]
In H3VR objects that you can pick up and throw around use the `FVRPhysicalObject` component. It would be possible for us to add a proxy for this component into WurstMod, but in the meantime it is possible in another way. Using a tool such as [uTinyRipper](https://github.com/mafaca/UtinyRipper) you can extract stubbed versions of the game's scripts and import them directly into your Unity project to use as normal. Unfortunately I don't have any guide that covers this in more detail.

Pointable button is a special component that converts a standard Unity UI button to one that you can actually point at. It re-uses the standard Unity button component's OnClick event, so anything you want to call when it is pressed goes there.

**Comment by adolfobisi** [comment]
Nice, that was helpful! Now I can do menu and buttons. 
Now about the anvil prefabs, in the spawnable list i cant seem to find the clay pigeon discs, clay pots or soda can. Are they actually on the list? Since its a extensive list and not in alphabetical order its kind of hard to find an expecific item. I'm modeling the shooting range near my house, so i'll try to recreate what anton did in the friendly 45 scene with the skeet launcher, and put it in my scene.

**Comment by Nolenz** [comment]
Certain objects might not be on the list due to the roundabout way the list is populated. I will see if those objects can be added next time I regenerate the file.

**Comment by nrgill28** [comment]
System has been refactored and all (current) `FVRObject` assets will be included in the next release. This includes clay pots, pigeons, and the sodas.

**Comment by adolfobisi** [comment]
> System has been refactored and all (current) `FVRObject` assets will be included in the next release. This includes clay pots, pigeons, and the sodas.

Nice! this will help a lot. Is it going to be in alphabetical order?
Sorry if this is a stupid question, i am not used to github very much, but a few weeks ago i downloaded the 2.0 version of WM and it came with the workbench package filled with scripts and plugins, and also a new sandbox debug scene, with the 3 anvil prefabs and different reverb enviroments, but in the 2 last releases the package comes with an older version, i think its v1.3, without some plugins and with the old debug scene, the one that has the sphere with particle gererator. Is there any reason for that? should i use this instead of the 2.0? Im learning unity just to make those maps so it gets a little confusing sometimes =)

**Comment by nrgill28** [comment]
No, the objects won't be in alphabetical order , but they are in categorical order and there is also a search box.

I would also not recommend using older versions of the workbench because a fair bit of stuff has been changed since then. It is possible to update your project from the older version, but unless you know what you're doing I'd just recommend opening a new Unity project with the most recent workbench.
