### ISSUE TITLE
WurstMod source.zip contains old version of WurstModWorkbench.unitypackage

### ISSUE THREAD

**Issue by GarretPolk** [Nolenz/WurstMod#29]
It appears that the WurstMod 2.0.0.0 and 2.0.2.0 (and I'd assume 2.0.1.0) "source.zip" files there's a WurstModWorkbench.unitypackage that is an older version. Probably 1.x version from the looks of it. The 2.0 Unity package linked directly from GitHub is 385KB and the one inside the source.zip is only 260KB. The Export menu functionality is missing from the source.zip version and has older scripts.

**Comment by nrgill28** [comment]
Ah, thanks for noticing this. In the next release I will make sure the workbench is updated and available for download on that release instead of also linking back to the older one and telling people to upgrade the dll.
