### ISSUE TITLE
Sosig spawner and whizz banger machine not showing up

### ISSUE THREAD

**Issue by CDJ-3000** [Nolenz/WurstMod#33]
So I'm trying to make a small sandbox scene just to play around in, but when I tested it the sosig spawner and banger machine didn't show up.  Also the item spawner didn't show unless I reloaded the scene, the other stuff still didn't spawn in tho.

I'm pretty new to this so I don't know if I'm doing anything wrong.  I just dragged the GenericPrefab objects in and set them to the spawner and stuff.

**Comment by nrgill28** [comment]
The item spawner sometimes requiring a scene reload is a known issue. This is the first time I've heard the other two are having issues as well - although they are rarely used so maybe that issue just hasn't surfaced until now. 

If the error is reproducible, In the BepInEx config file (`h3vr/BepInEx/configs/BepInEx.cfg`) on line 72, enable writing Unity logs to disk then reproduce the error and upload your bepinex log. I have an idea of where an error like this might come from but would like to confirm.

**Comment by CDJ-3000** [comment]
[LogOutput.log](https://github.com/WurstModders/WurstMod/files/6438510/LogOutput.log)
Ok here's the log file.

**Comment by nrgill28** [comment]
Huh, okay that's not the exact error I was expecting but it's specific enough that the fix should be fairly simple. I will have this fixed in the next release.

**Comment by nrgill28** [comment]
Should be fixed in WurstMod 2.2
