### ISSUE TITLE
Folder placement

### ISSUE THREAD

**Issue by OnyxInc** [Nolenz/WurstMod#4]
In the install instructions, it says to unzip both BepInEx and WurstMod into the H3 folder - but in the provided image, there's no WurstMod folder, and a CustomLevels folder that's not in this download or ever mentioned in the installation process. Is Wurstmod meant to be copied into BepInEx, and if so, where?

**Comment by Nolenz** [comment]
The [file in releases](https://github.com/Nolenz/WurstMod/releases/download/v1.2.0.0a/WurstMod_1.2.0.0.zip) is an archive containing the folder structure WurstMod needs, including the CustomLevels folder. 

It sounds to me like your archive tool is making parent folders when you extract things. If you're getting a WurstMod folder when you extract, you need to put everything in _that_ folder into the H3VR folder. 

If you use 7Zip, the context option to do this directly is "Extract Here" with WurstMod_1.2.0.0.zip in your H3VR folder.

**Comment by OnyxInc** [comment]
Thanks! The one I downloaded gave me the folders "generic" "properties" and "TNH" in a folder named "WurstMod".
I might just not know how GitHub works.
