### ISSUE TITLE
Information regarding bullet penetration 

### ISSUE THREAD

**Issue by allison-casey** [Nolenz/WurstMod#5]
Can't seem to find any information regarding bullet penetration. Is this something you have figured out or still an open question? Thanks again for the wonderful mod!

**Comment by Nolenz** [comment]
PMat is the closest I can think of that might control this, but I haven't played with it enough. There are a few tooltips on the PMat dropdowns with my notes.

**Comment by allison-casey** [comment]
so it looks like the first Def is what defines the hit effect (wood chips, dirt, etc) and the MatDef defines the actual penetration properties of the material. 

![pmat-test](https://user-images.githubusercontent.com/18231154/86312083-e0201c00-bbef-11ea-9b45-351bf83759f1.png)

**Comment by nrgill28** [comment]
Moved to the [Material properties](https://github.com/Nolenz/WurstMod/wiki/Material-Properties-(PMat)) page on the wiki
