### ISSUE TITLE
Excessively Large Map File Sizes

### ISSUE THREAD

**Issue by Searangerx** [Nolenz/WurstMod#6]
The assetbundles that are being packed for maps seems to be excessively large.

Even with a single 1k texture atlas I'm reaching file sizes of 200mb+

I've worked with assetbundles for other games and usually they pack much smaller then this even with hundreds of different textures.

**Comment by Nolenz** [comment]
I've noticed the same. As far as I can tell from a glance, this is just [Unity including all the nonsense it needs so it can load things at runtime](https://forum.unity.com/threads/size-of-assetbundle-is-larger-than-expected.438821/).

I'd like to look into it a bit more, but it's not super high priority currently. Which games have you worked with that produce smaller bundles?

**Comment by nrgill28** [comment]
This could be mitigated slightly by not using the uncompressed asset bundle option when exporting.
In my testing, it helps a lot with simpler maps (Taking the provided GenericDebug level from 299KB to just 65KB), though more complex maps with their own resources don't receive the same compression ratios.

**Comment by nrgill28** [comment]
Closing this because it's been mitigated by using compressed asset bundles in WurstMod 2.
